[package]
authors = ["Daniel Franklin <daniel@danielzfranklin.org>"]
edition = "2018"
name = "monitor-control-win"
version = "0.1.0"

[dependencies]
thiserror = "1.0.24"
windows = "0.7.0"

[build-dependencies]
windows = "0.7.0"
